server:
  port: 9091

spring:
  application:
    name: springcloud-eureka-client
  datasource:
      url: jdbc:oracle:thin:@localhost:1521/orcl
      username: system
      password: system
      driver-class-name: oracle.jdbc.OracleDriver

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9090/eureka/

mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml